--- mm/Makefile
+++ mm/Makefile
@@ -66,4 +66,3 @@ obj-$(CONFIG_GENERIC_EARLY_IOREMAP) += early_ioremap.o
 obj-$(CONFIG_ZPOOL)	+= zpool.o
 obj-$(CONFIG_ZSMALLOC)	+= zsmalloc.o
 obj-$(CONFIG_FORCE_RECLAIM)	+= force_reclaim.o
-obj-$(CONFIG_PROCESS_RECLAIM)	+= process_reclaim.o
--- mm/Makefile
+++ mm/Makefile
@@ -65,4 +65,3 @@ obj-$(CONFIG_Z3FOLD)	+= z3fold.o
 obj-$(CONFIG_GENERIC_EARLY_IOREMAP) += early_ioremap.o
 obj-$(CONFIG_ZPOOL)	+= zpool.o
 obj-$(CONFIG_ZSMALLOC)	+= zsmalloc.o
-obj-$(CONFIG_FORCE_RECLAIM)	+= force_reclaim.o
